version: '3.5'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 443:443
    networks:
      - inception-network
    volumes:
      - wordpress-data:/var/www/html
    env_file:
      - .env
    depends_on:
      - wordpress

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    ports:
      - 9000:9000
    networks:
      - inception-network
    volumes:
      - wordpress-data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_NAME=${MYSQL_WP_DATABASE}
      - WORDPRESS_DB_USER=${MYSQL_WP_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_WP_PASSWORD}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_TITLE=${WP_TITLE}
      - WP_URL=${WP_URL}
      - WP_USER=${WP_USER}
      - WP_EMAIL=${WP_EMAIL}
      - WP_PASSWORD=${WP_PASSWORD}
    env_file:
      - .env
    depends_on:
      - mariadb

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    networks:
      - inception-network
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_WP_USER=${MYSQL_WP_USER}
      - MYSQL_WP_DATABASE=${MYSQL_WP_DATABASE}
      - MYSQL_WP_PASSWORD=${MYSQL_WP_PASSWORD}
    env_file:
      - .env

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      device: /home/mpeharpr/data/wordpress
      o: bind

  mariadb-data:
    driver: local
    driver_opts:
      type: none
      device: /home/mpeharpr/data/mariadb
      o: bind

networks:
  inception-network:
  